# Generated by Django 3.2.7 on 2021-10-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusuario',
            name='nameuser',
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='username',
            field=models.CharField(max_length=60, unique=True, verbose_name='Nome usuario'),
        ),
    ]
